language: go

go:
    - 1.5
    - 1.6
    - 1.7
    - tip

before_install:
    mkdir $GOPATH/bin

install:
    curl https://glide.sh/get | sh

before_script:
    make get_deps

script:
    make test
    make clean
