language: go

go:
    - 1.9

services:
    - mongodb
    - redis-server

before_install:
    mkdir $GOPATH/bin

install:
    curl https://glide.sh/get | sh

before_script:
    make get_deps

script:
    make test
